force-app/main/default/objects/Team__c/Team__c.object-meta.xml
<CustomObject>
    <label>Team</label>
    <nameField>
        <label>Team Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Teams</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/TeamMember__c/TeamMember__c.object-meta.xml
<CustomObject>
    <label>Team Member</label>
    <nameField>
        <label>Team Member Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Team Members</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/TeamMember__c/fields/Skills__c.field-meta.xml
<CustomField>
    <fullName>Skills__c</fullName>
    <label>Skills</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/TeamMember__c/fields/Team__c.field-meta.xml
<CustomField>
    <fullName>Team__c</fullName>
    <label>Team</label>
    <referenceTo>Team__c</referenceTo>
    <relationshipLabel>Team Members</relationshipLabel>
    <relationshipName>TeamMembers</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/classes/TeamServiceImpl.cls
public with sharing class TeamServiceImpl implements TeamService.API {
	public List<TeamService.TeamWrapper> getTeams() {
		List<TeamService.TeamWrapper> teams = new List<TeamService.TeamWrapper>();
		for (Team__c team : [SELECT Id, Name FROM Team__c]) {
			teams.add(new TeamService.TeamWrapper(team));
		}
		return teams;
	}

	public void createTeamMember(TeamService.TeamMemberWrapper teamMember) {
		insert new TeamMember__c(
			Name = teamMember.Name,
			Skills__c = teamMember.Skills,
			Team__c = teamMember.TeamId
		);
	}

	public static List<TeamService.TeamMemberWrapper> getAllTeamMembers() {
		List<TeamService.TeamMemberWrapper> teamMembers = new List<TeamService.TeamMemberWrapper>();
		for (TeamMember__c teamMember : [
			SELECT Id, Name, Skills__c, Team__r.Id, Team__r.Name
			FROM TeamMember__c
			ORDER BY Name ASC
		]) {
			teamMembers.add(new TeamService.TeamMemberWrapper(teamMember));
		}
		return teamMembers;
	}
}