force-app/main/default/objects/Team__c/Team__c.object-meta.xml
<CustomObject>
    <label>Team</label>
    <nameField>
        <label>Team Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Teams</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/TeamMember__c/TeamMember__c.object-meta.xml
<CustomObject>
    <label>Team Member</label>
    <nameField>
        <label>Team Member Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Team Members</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/TeamMember__c/fields/Skills__c.field-meta.xml
<CustomField>
    <fullName>Skills__c</fullName>
    <label>Skills</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/TeamMember__c/fields/Team__c.field-meta.xml
<CustomField>
    <fullName>Team__c</fullName>
    <label>Team</label>
    <referenceTo>Team__c</referenceTo>
    <relationshipLabel>Team Members</relationshipLabel>
    <relationshipName>TeamMembers</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/classes/TeamService.cls
public with sharing class TeamService {
	private static final Type impl = TeamServiceImpl.class;

	@TestVisible
	private static final API mockImpl;

	public interface API {
		List<TeamService.TeamWrapper> getTeams();
		void createTeamMember(TeamService.TeamMemberWrapper teamMember);
		List<TeamService.TeamMemberWrapper> getAllTeamMembers();
	}

	private static API service() {
		return mockImpl != null ? mockImpl : (API) impl.newInstance();
	}

	public static List<TeamService.TeamWrapper> getTeams() {
		return service().getTeams();
	}

	public static void createTeamMember(TeamService.TeamMemberWrapper teamMember) {
		service().createTeamMember(teamMember);
	}

	public static List<TeamService.TeamMemberWrapper> getAllTeamMembers() {
		return service().getAllTeamMembers();
	}

	public class TeamWrapper {
		@AuraEnabled
		public String Id;

		@AuraEnabled
		public String Name;

		public TeamWrapper(Team__c team) {
			this.Id = team.Id;
			this.Name = team.Name;
		}
	}

	public class TeamMemberWrapper {
		@AuraEnabled
		public String Id;

		@AuraEnabled
		public String Name;

		@AuraEnabled
		public String Skills;

		@AuraEnabled
		public String TeamId;

		@AuraEnabled
		public String TeamName;

		public TeamMemberWrapper(TeamMember__c teamMember) {
			this.Id = teamMember.Id;
			this.Name = teamMember.Name;
			this.Skills = teamMember.Skills__c;
			this.TeamId = teamMember.Team__r.Id;
			this.TeamName = teamMember.Team__r.Name;
		}
	}
}